### ISSUE TITLE
Length profile improvements

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#275]
* [ ] export to DXF #20
* [ ] print function #19
* [ ] make sure the dock is visible when showing a profile #137 
* [ ] zoom to profile exten #128 
* [ ] provide manhole and section details (dimensions, depth, material, slope, etc)  #17

**Comment by urskaufmann** [comment]
Some problems with the length profile:
- if you define it with two selections, you have not the same result as defining it with one selection:
![qgep-laengenprofil-2selections](https://user-images.githubusercontent.com/1257403/27276920-ed655dc6-54dc-11e7-93cd-d9eda32e5739.JPG)
![qgep-laengenprofil_1selection](https://user-images.githubusercontent.com/1257403/27276937-faaef3ca-54dc-11e7-80ba-563654197b97.JPG)
The surface-line (green line) is not correct at the start of the length profile and at the manhole, where the second selection starts (in the example the manhole ZE2J1). 

- the information about the manhole showes no out-level available. But there is a level at the from-reach-point (this level is correct shown in the reach-information).

- the information about the manhole shows not the identifer but the obj_id
