### ISSUE TITLE
[Datamodel] Rework QGEP datamodel mechanics

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#414]
Here is a central issue to gather main problematic db issues with actual QGEP datamodel in terms of edition:

 - [ ] Covers are mandatory in wastewater structure construction https://github.com/QGEP/QGEP/issues/371
 - [ ] "Radier" object cannot be described properly : material, default
 - [ ] Chanels in wastewaterstructure view https://github.com/QGEP/QGEP/issues/405
 - [ ] Deleting a feature in vw_qgep_reach does not delete relative reach points https://github.com/QGEP/QGEP/issues/333 Linked to https://github.com/QGEP/QGEP/issues/143
 - [ ] Materialized views are not usable at start https://github.com/QGEP/QGEP/issues/409

Feel free to edit my post and list actually encountered issues.

**Edit** : 02.05.2018 ponceta

**Comment by sjib** [comment]
What do you mean with: "Radier" object cannot be described properly : material, default
Do you mean Bankett / benching / BANQUETTE? Would you like another attribute there besides kind?

**Comment by ponceta** [comment]
With "radier" I mean Sohle in german, I do not know the english translation.

For now, I'll go with a bottom_material (which is relevant when different from the wasterwater structure material).

**Comment by ponceta** [comment]
I close this since following Datamodel tag is sufficient for this use case.
